--- CREACION DE BASE DE DATOS, ESQUEMA, TABLAS //////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE DATABASE [DB_CLUB_CAMPESTRE_UAM]
GO

USE [DB_CLUB_CAMPESTRE_UAM]
GO

-- ESQUEMAS
CREATE SCHEMA [SCH_CLUB]
GO

CREATE SCHEMA [SCH_PERSONA]
GO

--TABLA CLUB = Padre
CREATE TABLE [SCH_CLUB].[TB_CLUB]--ELIMINAR TABLA
(
 [CED_JUR]  CHAR(10)      NOT NULL,
 [NOMBRE]   NVARCHAR(20)  NOT NULL,
 [TEL]      CHAR(8)       NOT NULL,
 [E_MAIL]   VARCHAR(30)   NOT NULL
 CONSTRAINT [PK_CLUB] PRIMARY KEY CLUSTERED
  (
   [CED_JUR] ASC
  )
)
GO

--TABLA CLIENTE = Padre
CREATE TABLE [SCH_PERSONA].[TB_CLIENTES]
(
 [CED]      CHAR(9)         NOT NULL,
 [NOMBRE]   NVARCHAR(10)    NOT NULL,
 [APELLIDO] NVARCHAR(15)    NOT NULL,
 [EDAD]     TINYINT         NOT NULL,
 [GENERO]   VARCHAR(30)     NOT NULL--ELIMINAR
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED
 (
  [CED] ASC
 )
)
GO

--TABLA TIPO DE HABITACION = Padre
CREATE TABLE [SCH_CLUB].[TB_TIPO_HABITACIONES]
(
[CODIGO]             TINYINT       NOT NULL,
[MODELO]             VARCHAR(15)   NOT NULL,
[CANT_CAMAS]         TINYINT       NOT NULL, -- CANTIDDAD DE CAMAS POR HABITACION
[CANT_HABITACIONES]  TINYINT       NOT NULL,
[TV]                 BIT           NOT NULL, -- SI TIENE O NO TIENE
[JACUZZI]            BIT           NOT NULL,
[PRECIO]             MONEY         NOT NULL
 CONSTRAINT [PK_TIPO_HABITACIONES] PRIMARY KEY CLUSTERED
 (
  [CODIGO] ASC
 )
)

GO

--TABLA HABITACION = Hijo
CREATE TABLE [SCH_CLUB].[TB_HABITACIONES]
(
[NUM_HABITACION]     INT      NOT NULL,
[TIPO_HABITACION]    TINYINT  NOT NULL --FK
 CONSTRAINT [PK_HABITACION] PRIMARY KEY CLUSTERED
 (
  [NUM_HABITACION] ASC
 )
)
GO

--FK's
ALTER TABLE [SCH_CLUB].[TB_HABITACIONES] 
ADD CONSTRAINT [FK_TIPO_HABITACION] FOREIGN KEY ([TIPO_HABITACION]) 
REFERENCES [SCH_CLUB].[TB_TIPO_HABITACIONES]([CODIGO])
GO
ALTER TABLE [SCH_CLUB].[TB_HABITACIONES]  CHECK CONSTRAINT
[FK_TIPO_HABITACION]
GO

--TABLA RESERVA = Hijo
CREATE TABLE [SCH_CLUB].[TB_RESERVAS]
(
 [RESERVA_ID]         INT       NOT NULL,
 [CANT_PERSONAS]      TINYINT   NOT NULL,
 [FECHA]			  DATETIME  NOT NULL,
 [CLIENTE]			  CHAR(9)   NOT NULL, --FK
 [HABITACION]         INT		NOT NULL, --FK
 [EMPRESA]			  CHAR(10)  NOT NULL, --FK
 CONSTRAINT [PK_RESERVAS] PRIMARY KEY CLUSTERED
 (
  [RESERVA_ID] ASC
 )
)
GO

--FK's
ALTER TABLE [SCH_CLUB].[TB_RESERVAS] 
ADD CONSTRAINT [FK_TB_RESERVAS_CLIENTE] FOREIGN KEY ([CLIENTE]) 
REFERENCES [SCH_PERSONA].[TB_CLIENTES]([CED])

GO
ALTER TABLE [SCH_CLUB].[TB_RESERVAS]  CHECK CONSTRAINT
[FK_TB_RESERVAS_CLIENTE]
GO

ALTER TABLE [SCH_CLUB].[TB_RESERVAS] 
ADD CONSTRAINT [FK_TB_RESERVAS_HABITACION] FOREIGN KEY ([HABITACION]) 
REFERENCES [SCH_CLUB].[TB_HABITACIONES]([NUM_HABITACION])
GO
ALTER TABLE [SCH_CLUB].[TB_RESERVAS] CHECK CONSTRAINT
[FK_TB_RESERVAS_HABITACION]
GO

ALTER TABLE [SCH_CLUB].[TB_RESERVAS] 
ADD CONSTRAINT [FK_TB_RESERVAS_EMPRESA]	FOREIGN KEY ([EMPRESA]) 
REFERENCES [SCH_CLUB].[TB_CLUB]([CED_JUR])
GO
ALTER TABLE [SCH_CLUB].[TB_RESERVAS]  CHECK CONSTRAINT
[FK_TB_RESERVAS_EMPRESA]
GO

--TABLA SERVICIOS = Hijo
CREATE TABLE [SCH_CLUB].[TB_SERVICIOS]
(
[SERVICIO_ID]        INT              NOT NULL,
[TIPO_SERVICIO]      NVARCHAR(30)     NOT NULL,
[EMPRESA]			 CHAR(10)		  NOT NULL --FK
 CONSTRAINT [PK_SERVICIOS] PRIMARY KEY CLUSTERED
 (
  [SERVICIO_ID] ASC
 )
)
GO

--FK's
ALTER TABLE [SCH_CLUB].[TB_SERVICIOS] 
ADD CONSTRAINT [FK_TB_SERVICIOS_EMPRESA] FOREIGN KEY ([EMPRESA]) 
REFERENCES [SCH_CLUB].[TB_CLUB]([CED_JUR])
GO
ALTER TABLE [SCH_CLUB].[TB_SERVICIOS] CHECK CONSTRAINT
[FK_TB_SERVICIOS_EMPRESA]
GO

--TABLA COLABORADOR = Hijo 
CREATE TABLE [SCH_PERSONA].[TB_COLABORADOR]
(
 [COLABORADOR_ID]       INT        NOT NULL,
 [CEDULA]               CHAR(9)    NOT NULL,
 [NOMBRE]   VARCHAR(10)    NOT NULL,
 [APELLIDO] VARCHAR(15)    NOT NULL,
 [EDAD]     TINYINT        NOT NULL,
 [GENERO]   VARCHAR(30)    NOT NULL,
 [EMPRESA]  CHAR(10)   	   NOT NULL --FK
 CONSTRAINT [PK_COLABORADOR] PRIMARY KEY CLUSTERED
 (
  [COLABORADOR_ID] ASC
 )
)
GO

--FK's
ALTER TABLE [SCH_PERSONA].[TB_COLABORADOR] 
ADD CONSTRAINT [FK_TB_COLABORADOR_EMPRESA] FOREIGN KEY ([EMPRESA]) 
REFERENCES [SCH_CLUB].[TB_CLUB]([CED_JUR])
GO
ALTER TABLE [SCH_PERSONA].[TB_COLABORADOR]  CHECK CONSTRAINT
[FK_TB_COLABORADOR_EMPRESA]
GO

--TABLA FACTURA = Hijo
CREATE TABLE [SCH_CLUB].[TB_FACTURA]
(
[COD_FACTURA]     INT           NOT NULL,
[FECHA]           DATETIME      NOT NULL,
[DIRECCION]       VARCHAR(100)  NOT NULL,
[CLIENTE]		  CHAR(9)	    NOT NULL, --FK
[TIPO_HABITACION] TINYINT		NOT NULL  --FK (1=BASICA,2=ESTANDAR,3=SUPREMA)
	CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED
	(
	  [COD_FACTURA] ASC
	)
)
GO

INSERT INTO[SCH_CLUB].[TB_FACTURA]
([COD_FACTURA],[FECHA],[DIRECCION],[CLIENTE],[TIPO_HABITACION])
VALUES(55,SYSDATETIME(),'5 PLANTA - BLOQUECB','305080556',2)
GO

--FK's
ALTER TABLE [SCH_CLUB].[TB_FACTURA] 
ADD CONSTRAINT [FK_TB_FACTURA_CLIENTE] FOREIGN KEY ([CLIENTE]) 
REFERENCES [SCH_PERSONA].[TB_CLIENTES]([CED])
GO
ALTER TABLE [SCH_CLUB].[TB_FACTURA] CHECK CONSTRAINT
[FK_TB_FACTURA_CLIENTE]
GO

ALTER TABLE [SCH_CLUB].[TB_FACTURA] 
ADD CONSTRAINT [FK_TB_FACTURA_TIPO_HABITACION] FOREIGN KEY ([TIPO_HABITACION]) 
REFERENCES [SCH_CLUB].[TB_TIPO_HABITACIONES]([CODIGO])
GO
ALTER TABLE [SCH_CLUB].[TB_FACTURA] CHECK CONSTRAINT
[FK_TB_FACTURA_TIPO_HABITACION]
GO

--METODO DE ALMACENADO
-- TABLA [SCH_PERSONA].[TB_CLIENTES]
CREATE PROCEDURE SP_INSERTAR_CLIENTE
@CED        CHAR(9),
@NOMBRE   NVARCHAR(10),
@APELLIDO NVARCHAR(15),
@EDAD     TINYINT, 
@GENERO   VARCHAR(30)
AS
INSERT INTO [SCH_PERSONA].[TB_CLIENTES]([CED],[NOMBRE],[APELLIDO],[EDAD],[GENERO])
VALUES(@CED,@NOMBRE,@APELLIDO,@EDAD,@GENERO)
GO