--- CREACION DE BASE DE DATOS, ESQUEMA, TABLAS //////////////////////////////////////////////////////////////////////////////////////////////////////////
CREATE DATABASE [DB_CLUB_CAMPESTRE_UAM]
GO

USE [DB_CLUB_CAMPESTRE_UAM]
GO
---------------------------------------------------------------
-- ESQUEMAS
CREATE SCHEMA [SCH_CLUB]
GO

CREATE SCHEMA [SCH_PERSONA]
GO
---------------------------------------------------------------
--TABLA CLIENTE = Padre
CREATE TABLE [SCH_PERSONA].[TB_CLIENTES]
(
 [CED]      CHAR(9)         NOT NULL,
 [NOMBRE]   NVARCHAR(10)    NOT NULL,
 [APELLIDO] NVARCHAR(15)    NOT NULL,
 [EDAD]     TINYINT         NOT NULL,
 [TEL]      INT             NOT NULL
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED
 (
  [CED] ASC
 )
)
GO
---------------------------------------------------------------
--TABLA TIPO DE HABITACION = PADRE
CREATE TABLE [SCH_CLUB].[TB_TIPO_HABITACIONES]
(
[MODELO]             VARCHAR(15)   NOT NULL,
[CANT_CAMAS]         TINYINT       NOT NULL, -- CANTIDDAD DE CAMAS POR HABITACION
[CANT_HABITACIONES]  TINYINT       NOT NULL,
[PRECIO_HABITACION]  MONEY         NOT NULL
 CONSTRAINT [PK_TIPO_HABITACIONES] PRIMARY KEY CLUSTERED
 (
  [MODELO] ASC
 )
)
GO

---------------------------------------------------------------
--TABLA SERVICIOS = PADRE
CREATE TABLE [SCH_CLUB].[TB_SERVICIOS]
(
[TIPO_SERVICIO]      NVARCHAR(30)     NOT NULL,
[TV]                 BIT              NOT NULL,
[JACUZZI]            BIT              NOT NULL,
[MINI_BAR]           BIT              NOT NULL,
[SERV_HABITACION]    BIT              NOT NULL,
[PRECIO_SERVICIO]    MONEY            NOT NULL
 CONSTRAINT [PK_SERVICIOS] PRIMARY KEY CLUSTERED
 (
  [TIPO_SERVICIO] ASC
 )
)
GO

---------------------------------------------------------------
--TABLA RESERVA = Hijo
CREATE TABLE [SCH_CLUB].[TB_RESERVAS]
(
 [RESERVA_ID]           INT            NOT NULL,
 [CANT_PERSONAS]        TINYINT        NOT NULL,
 [FECHA]			    DATETIME       NOT NULL,
 [NUM_HABITACION]       INT            NOT NULL,
 [CED_CLIENTE]			CHAR(9)        NOT NULL, --FK
 [HABITACION_RESERVADA] VARCHAR(15)    NOT NULL, --FK
 [SERVICIO_RESERVADO]   NVARCHAR(30)   NOT NULL  --FK
 CONSTRAINT [PK_RESERVAS] PRIMARY KEY CLUSTERED
 (
  [RESERVA_ID] ASC
 )
)
GO

ALTER TABLE [SCH_CLUB].[TB_RESERVAS] 
ADD CONSTRAINT [FK_CLIENTES_RESERVAS_CED_CLIENTE] FOREIGN KEY ([CED_CLIENTE]) 
REFERENCES [SCH_PERSONA].[TB_CLIENTES]([CED])

GO
ALTER TABLE [SCH_CLUB].[TB_RESERVAS]  CHECK CONSTRAINT
[FK_CLIENTES_RESERVAS_CED_CLIENTE]
GO

ALTER TABLE [SCH_CLUB].[TB_RESERVAS] 
ADD CONSTRAINT [FK_TIPO_HABITACIONES_RESERVAS_HABITACION_RESERVADA] FOREIGN KEY ([HABITACION_RESERVADA]) 
REFERENCES [SCH_CLUB].[TB_TIPO_HABITACIONES]([MODELO])
GO
ALTER TABLE [SCH_CLUB].[TB_RESERVAS]  CHECK CONSTRAINT
[FK_TIPO_HABITACIONES_RESERVAS_HABITACION_RESERVADA]
GO

ALTER TABLE [SCH_CLUB].[TB_RESERVAS] 
ADD CONSTRAINT [FK_SERVICIOS_RESERVAS_SERVICIO_RESERVADO] FOREIGN KEY ([SERVICIO_RESERVADO]) 
REFERENCES [SCH_CLUB].[TB_SERVICIOS]([TIPO_SERVICIO])
GO
ALTER TABLE [SCH_CLUB].[TB_RESERVAS]  CHECK CONSTRAINT
[FK_SERVICIOS_RESERVAS_SERVICIO_RESERVADO]
GO
---------------------------------------------------------
--TABLA FACTURA = Hijo
CREATE TABLE [SCH_CLUB].[TB_FACTURA]
(
[COD_FACTURA]             INT           NOT NULL,
[FECHA]                   DATETIME      NOT NULL,
[TOTAL]                   MONEY         NOT NULL,
[CED_CLIENTE]             CHAR(9)       NOT NULL,--FK
[HABITACION_FACTURADA]    VARCHAR(15)   NOT NULL,--FK
[SERVICIO_FACTURADO]      NVARCHAR(30)	NOT NULL --FK
	CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED
	(
	  [COD_FACTURA] ASC
	)
)
GO

ALTER TABLE [SCH_CLUB].[TB_FACTURA] 
ADD CONSTRAINT [FK_CLIENTES_FACTURA_CED_CLIENTE] FOREIGN KEY ([CED_CLIENTE]) 
REFERENCES [SCH_PERSONA].[TB_CLIENTES]([CED])
GO
ALTER TABLE [SCH_CLUB].[TB_FACTURA] CHECK CONSTRAINT
[FK_CLIENTES_FACTURA_CED_CLIENTE]
GO

ALTER TABLE [SCH_CLUB].[TB_FACTURA] 
ADD CONSTRAINT [FK_TIPO_HABITACIONES_FACTURA_HABITACION_FACTURADA] FOREIGN KEY ([HABITACION_FACTURADA]) 
REFERENCES [SCH_CLUB].[TB_TIPO_HABITACIONES]([MODELO])
GO
ALTER TABLE [SCH_CLUB].[TB_FACTURA] CHECK CONSTRAINT
[FK_TIPO_HABITACIONES_FACTURA_HABITACION_FACTURADA]
GO

ALTER TABLE [SCH_CLUB].[TB_FACTURA] 
ADD CONSTRAINT [FK_SERVICIOS_FACTURA_SERVICIO_FACTURADO] FOREIGN KEY ([SERVICIO_FACTURADO]) 
REFERENCES [SCH_CLUB].[TB_SERVICIOS]([TIPO_SERVICIO])
GO
ALTER TABLE [SCH_CLUB].[TB_FACTURA] CHECK CONSTRAINT
[FK_SERVICIOS_FACTURA_SERVICIO_FACTURADO]
GO
---------------------------------------------------------------
--TABLAS PADRES
USE [DB_CLUB_CAMPESTRE_UAM]
GO

INSERT INTO [SCH_PERSONA].[TB_CLIENTES]
([CED],[NOMBRE],[APELLIDO],[EDAD],[TEL])
VALUES('604420119','DAVID','MESEN',25,83175302)
GO

INSERT INTO [SCH_PERSONA].[TB_CLIENTES]
([CED],[NOMBRE],[APELLIDO],[EDAD],[TEL])
VALUES('504580147','WALTER','VARGAS',26,84651455)
GO

INSERT INTO [SCH_PERSONA].[TB_CLIENTES]
([CED],[NOMBRE],[APELLIDO],[EDAD],[TEL])
VALUES('105470145','LUIS','ROJAS',24,78965421)
GO

--DML'S [SCH_CLUB].[TB_TIPO_HABITACIONES
INSERT INTO [SCH_CLUB].[TB_TIPO_HABITACIONES]
([MODELO],[CANT_CAMAS],[CANT_HABITACIONES],[PRECIO_HABITACION])
VALUES('CUARTO',1,1,25000.00)
GO

INSERT INTO [SCH_CLUB].[TB_TIPO_HABITACIONES]
([MODELO],[CANT_CAMAS],[CANT_HABITACIONES],[PRECIO_HABITACION])
VALUES('CABINA',2,1,50000.00)
GO

INSERT INTO [SCH_CLUB].[TB_TIPO_HABITACIONES]
([MODELO],[CANT_CAMAS],[CANT_HABITACIONES],[PRECIO_HABITACION])
VALUES('CABA_A',3,2,150000.00)
GO

---------------------------------------------------------------
--DML'S [SCH_CLUB].[TB_SERVICIOS]
INSERT INTO [SCH_CLUB].[TB_SERVICIOS]
([TIPO_SERVICIO],[TV],[JACUZZI],[MINI_BAR],[SERV_HABITACION],[PRECIO_SERVICIO])
VALUES('NINGUNO',0,0,0,0,0.00)
GO

INSERT INTO [SCH_CLUB].[TB_SERVICIOS]
([TIPO_SERVICIO],[TV],[JACUZZI],[MINI_BAR],[SERV_HABITACION],[PRECIO_SERVICIO])
VALUES('BASICO',1,0,0,1,15000.00)
GO

INSERT INTO [SCH_CLUB].[TB_SERVICIOS]
([TIPO_SERVICIO],[TV],[JACUZZI],[MINI_BAR],[SERV_HABITACION],[PRECIO_SERVICIO])
VALUES('INTERMEDIO',1,0,1,1,35000.00)
GO

INSERT INTO [SCH_CLUB].[TB_SERVICIOS]
([TIPO_SERVICIO],[TV],[JACUZZI],[MINI_BAR],[SERV_HABITACION],[PRECIO_SERVICIO])
VALUES('TODO INCLUIDO',1,1,1,1,67000.00)
GO

---------------------------------------------------------------
INSERT INTO [SCH_CLUB].[TB_RESERVAS]
([RESERVA_ID],[CANT_PERSONAS],[FECHA],[NUM_HABITACION],[CED_CLIENTE],[HABITACION_RESERVADA],[SERVICIO_RESERVADO])
VALUES(651,4,SYSDATETIME(),13,'604420119','CABA_A','TODO INCLUIDO')
GO

---------------------------------------------------------------
INSERT INTO [SCH_CLUB].[TB_FACTURA]
([COD_FACTURA],[FECHA],[TOTAL],[CED_CLIENTE],[HABITACION_FACTURADA],[SERVICIO_FACTURADO])
VALUES(002,SYSDATETIME(),217000.00,'504580147','CABA_A','TODO INCLUIDO')
GO

---------------------------------------------------------------
--METODOS DE ALMACENADO
CREATE PROCEDURE SP_INSERTAR_CLIENTES
 @CED      CHAR(9),
 @NOMBRE   NVARCHAR(10),
 @APELLIDO NVARCHAR(15),
 @EDAD     TINYINT,
 @TEL      INT
 AS
 INSERT INTO [SCH_PERSONA].[TB_CLIENTES]([CED],[NOMBRE],[APELLIDO],[EDAD],[TEL])
 VALUES(@CED,@NOMBRE,@APELLIDO,@EDAD,@TEL)
 GO
 ---------------------------------------------------------------
 CREATE PROCEDURE SP_INSERTAR_RESERVAS
 @RESERVA_ID            INT,
 @CANT_PERSONAS         TINYINT,
 @FECHA		   	        DATETIME,
 @NUM_HABITACION        INT,
 @CED_CLIENTE			CHAR(9),
 @HABITACION_RESERVADA  VARCHAR(15),
 @SERVICIO_RESERVADO    NVARCHAR(30)
 AS
 INSERT INTO [SCH_CLUB].[TB_RESERVAS]([RESERVA_ID],[CANT_PERSONAS],[FECHA],[NUM_HABITACION],[CED_CLIENTE],[HABITACION_RESERVADA],[SERVICIO_RESERVADO])
 VALUES(@RESERVA_ID,@CANT_PERSONAS,SYSDATETIME(),@NUM_HABITACION,@CED_CLIENTE,@HABITACION_RESERVADA,@SERVICIO_RESERVADO)
 GO
 ---------------------------------------------------------------
 CREATE PROCEDURE SP_INSERTAR_FACTURA
 @COD_FACTURA             INT,
 @FECHA                   DATETIME,
 @TOTAL                   MONEY,
 @CED_CLIENTE             CHAR(9),
 @HABITACION_FACTURADA    VARCHAR(15),
 @SERVICIO_FACTURADO      NVARCHAR(30)
 AS
 INSERT INTO [SCH_CLUB].[TB_FACTURA]([COD_FACTURA],[FECHA],[TOTAL],[CED_CLIENTE],[HABITACION_FACTURADA],[SERVICIO_FACTURADO])
 VALUES(@COD_FACTURA,@FECHA,@TOTAL,@CED_CLIENTE,@HABITACION_FACTURADA,@SERVICIO_FACTURADO)
 GO
 ---------------------------------------------------------------
 --SELECT'S
 
SELECT *
FROM [SCH_PERSONA].[TB_CLIENTES]
GO
---------------------------------------------------------------

SELECT *
FROM [SCH_CLUB].[TB_TIPO_HABITACIONES]
GO
---------------------------------------------------------------

SELECT *
FROM [SCH_CLUB].[TB_SERVICIOS]
GO
---------------------------------------------------------------

SELECT *
FROM [SCH_CLUB].[TB_RESERVAS]
GO
---------------------------------------------------------------

SELECT *
FROM [SCH_CLUB].[TB_FACTURA]
GO
---------------------------------------------------------------